# Budget Configuration
# All prices are in USDM (USD-pegged stablecoin on Masumi Network)
# 1 USDM = 1,000,000 lovelace
budget:
  total_budget: 20.0  # Total budget across all agents in USDM
  network: "Preprod"  # Network for Masumi transactions (Preprod/Mainnet)
  
# Available agents configuration
agents:

  - name: "audience-insights-gwi"
    endpoint: "http://138.68.88.241:8000/Audience%20Insights%20GWI"  
    description: "Global Web Index audience insights"
    price: 3.0  # Expected cost per job in USDM
    max_total_spend: 9.0  # Optional: can call this agent until 9.0 USDM is spent
    enabled: true
    
  - name: "advanced-web-research"
    endpoint: "http://138.68.88.241:8000/Advanced%20Web%20Research"
    description: "Advanced web research agent for comprehensive web research"
    price: 2.5  # Expected cost per job in USDM
    # No max_total_spend means only limited by total_budget
    enabled: true