# Budget Configuration
# All prices are in USDM (USD-pegged stablecoin on Masumi Network)
# 1 USDM = 1,000,000 lovelace
budget:
  total_budget: 30.0  # Total budget across all agents in USDM
  network: "Preprod"  # Network for Masumi transactions (Preprod/Mainnet)
  
# Available agents configuration
agents:

  - name: "audience-insights-gwi"
    endpoint: "http://138.68.88.241:8000/Audience%20Insights%20GWI"  
    description: "Global Web Index (GWI) consumer research platform providing deep audience insights from survey data. IMPORTANT: Use short, concise prompts for best results - complex questions yield fewer data points. Each response includes a Chat ID for follow-up queries."
    price: 3.0  # Expected cost per job in USDM
    max_total_spend: 9.0  # Optional: can call this agent until 9.0 USDM is spent
    enabled: true
    capabilities:
      - "Access to 250K+ consumer profiling points including demographics, psychographics, and behaviors"
      - "Country-specific data for 50+ markets including US, UK, Germany, Japan, Brazil, etc."
      - "Demographic segmentation by age (16-64), gender, income level, education, and location"
      - "Consumer attitudes, brand affinity, purchase intent, and lifestyle data"
      - "Media consumption habits, device usage, and online behavior patterns"
      - "Industry-specific insights for retail, finance, travel, technology, and more"
      - "Chat ID feature: Each response includes a Chat ID for follow-up questions to drill deeper"
    best_for: "Concise demographic descriptions, simple audience segments, follow-up queries using Chat IDs from previous responses. Works best with short prompts."
    example_prompts:
      - "male mid-level managers who are thinking about upgrading their car"
      - "millennial women in entry-level positions"
      - "Gen Z college students interested in sustainable fashion"
      - "Follow-up: Use Chat ID 3b60363c-4f37-4d27-983a-17dd487f77a3 to explore their media habits"
    limitations:
      - "Shorter prompts yield more data points (150+ for concise descriptions vs 5-10 for complex questions)"
      - "Avoid long, multi-part questions - break them into separate queries instead"
      - "Best results from simple demographic/psychographic descriptions rather than complex analytical questions"
      - "Use the Chat ID from responses for targeted follow-up questions in refinement phase"
    
  - name: "advanced-web-research"
    endpoint: "http://138.68.88.241:8000/Advanced%20Web%20Research"
    description: "Comprehensive web research agent that searches, analyzes, and synthesizes information from across the internet with source citations"
    price: 2.5  # Expected cost per job in USDM
    # No max_total_spend means only limited by total_budget
    enabled: true
    capabilities:
      - "Real-time web search across millions of sources including news, blogs, research papers, and reports"
      - "Statistical data gathering from authoritative sources and industry reports"
      - "Trend analysis and pattern identification from multiple data points"
      - "Expert opinion aggregation from thought leaders and industry publications"
      - "Competitive analysis and market research capabilities"
      - "Always provides source citations and links for verification"
      - "Can focus research on specific time periods (e.g., 'last 6 months', '2023-2024')"
    best_for: "Current trends, market statistics, competitive analysis, expert opinions, emerging patterns, fact-checking"
    example_prompts:
      - "What are the latest trends in sustainable furniture design and which brands are leading innovation in eco-friendly materials for nursery furniture?"
      - "Research the current market size and growth projections for baby furniture in North America, including key statistics on spending patterns for first-time parents"
      - "Find expert opinions and consumer reviews about the most important safety features parents look for when purchasing cribs and changing tables"
 
  - name: "ask-the-crowd"
    endpoint: "http://138.68.88.241:8000/Ask%20The%20Crowd"
    description: "EU-specific crowd opinion and survey platform with web search. Validates statements using real consumer feedback. Best used in refinement phase to test insights from initial research. The system will handle proper formatting based on the input schema."
    price: 2.0  # Expected cost per job in USDM
    max_total_spend: 8.0  # Can call this agent until 8.0 USDM is spent
    enabled: true
    capabilities:
      - "Survey analysis: Get responses on 5-point scale (strongly disagree to strongly agree) from EU consumers"
      - "Opinion soundbites: Collect 5 authentic consumer perspectives on your statement"
      - "Web search integration: Researches context before gathering opinions for more informed responses"
      - "Demographic targeting: Filter responses by gender and age range (18+ only) using separate input fields"
      - "EU market coverage: Data from major European Union countries only"
      - "Statement validation: Test hypotheses and insights discovered in initial research"
      - "Sentiment analysis: Understand how EU consumers feel about specific claims or trends"
    best_for: "Validating insights in refinement phase, testing statements with targeted demographics (via separate fields), getting EU-specific sentiment with web-informed context, adding human perspective to data findings"
    example_prompts:
      - "Sustainability is a key factor when purchasing baby furniture"
      - "Ergonomic home office furniture is worth the extra cost"
      - "Renting furniture is preferable to buying"
      - "Flexible work-from-home furniture solutions are essential"
      - "Brand reputation influences furniture purchasing decisions"
    limitations:
      - "EU countries only - no data from US, Asia, or other markets"
      - "Requires statement format (not questions) - frame as assertions to validate"
      - "Demographics are set via separate input fields (gender, age_min, age_max)"
      - "Write statements as you would present them to actual survey participants"
      - "Minimum age requirement: 18+ (enforced via age_min field)"
      - "Best results when used to validate specific findings from initial research"
      - "Limited to 5 opinion soundbites per query"
      - "Survey responses use 5-point scale (Strongly Disagree to Strongly Agree)"
 